routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/',function(){
    return view('welcome');
});
Route::group(['prefix'=>'client'],function(){


    Route::get('index',function(){
        return view('client.index');
    });
    Route::get('about',function(){
        return view('client.about');
    });
    Route::get('blog',function(){
        return view('client.blog');
    });
    Route::get('account',function(){
        return view('client.my-account');
    });
    Route::get('event',function(){
        return view('client.event-detail');
    });
});


Route::group(['prefix'=>'admin'],function(){

//slide controller
Route::resource('photos','PhotosController');

//company-details controller

Route::resource('company-details','CompanysController');

//find-job controller
Route::resource('find-job','FindJobController');

//trust-us controller
Route::resource('trust-us','TrustUsController');

//event controller
Route::resource('event','EventController');

//testimonial controller
Route::resource('testimonial','TestimonialController');

//team controller
Route::resource('team','TeamController');

//dashboard controller
Route::resource('dashboard','DashboardController');

//profile controller
Route::resource('profile','ProfileController');
});





Auth::routes();
Route::get('logout','Auth\LoginController@logout')->name('logout');
Route::get('/home', 'HomeController@index')->name('home');

app/Slide.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slide extends Model
{
    protected $fillable = array('text', 'cover_image');

    public function photos(){
      return $this->hasMany('App\Photo');
  }
}

resources/views/admin/slide/create.blade.php
@extends('layouts.admin-master')
@section('content')
                <!-- Content Wrapper START -->

                <div class="main-content">
                    <div class="container-fluid">
                        <div class="card">
                           <div class="col-md-12">
            <div class="panel panel-default">

              <div class="panel-body">
                <ul class="nav nav-pills m-b-30 ">
                <li class="active nav-item "> <a href="#navpills-2" class="nav-link" data-toggle="tab" aria-expanded="false">List</a> </li>
                  <li class="nav-item"> <a href="#navpills-1" class="nav-link" data-toggle="tab" aria-expanded="false">Add</a> </li>
                     </ul>
                <div class="tab-content br-n pn">
                  <div id="navpills-1" class="tab-pane">
                    <div class="row">
                      <div class="col-md-8">
                                 {!!Form::open(['action' => 'PhotosController@store','method' => 'POST', 'enctype' => 'multipart/form-data'])!!}
     <div class="form-group">
        <div class="col-sm-8">
     {!! Form::label('title','Title')!!}                            
    {{Form::text('name','',['class'=>'form-control'])}}
    </div>
</div>
<div class="form-group">
    <div class="col-sm-8">
    {{Form::file('cover_image',['class'=>'form-control'])}}
</div>
</div>
<div class="form-group">
    <div class="col-sm-2">
    {{Form::submit('submit',['class'=>'btn btn-primary'])}}
</div>
</div>
  {!! Form::close() !!}   
                                </div>
                               
                            </div>
                            
                                    
                                    </div>
                                    <div id="navpills-2" class="tab-pane active">
                  <div class="row">
                    <div class="table-responsive "><br><div class="col-md-8">@include('inc.message')</div><br>
                      <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered datatables" id="example">
                        <thead>
                          <tr>
                            <th class="center">Sl.</th>
                            <th class="center" >Title</th>
                            <th class="center">photo</th>

                            <th class="tdAction" align="center" width="120">Action</th>
                          </tr>
                        </thead>
                        <tbody>
                             @foreach($slides as $slide)
                          <tr class="odd" id="tR1">
                           
                            <td data-title="Serial"  width="30" align="right">{{$slide->id}}</td>
                           <td data-title="Serial"  >{{$slide->text}}</td>
                           

                            <td><img src="/album_covers/{{$slide->cover_image}}" width="100" height="60" alt="{{$slide->text}}"></td>

                            <td data-title="Action" align="center" width="120"><span id="deleteLoader1">&nbsp;</span>

                                
                              <a onclick="return confirm('Do you want to Edit?')" href="{{route('photos.edit',$slide->id)}}" class="btn btn-xs btn-green">
                    <i class="fa fa-pencil"></i>
                    </a>


                          {!!Form::open(['action' => ['PhotosController@destroy', $slide->id], 'method' => 'POST'])!!}
    {{Form::hidden('_method', 'DELETE')}}
    
                              {{Form::submit('Delete', ['class' => 'fa fa-trash-o'])}}
  {!!Form::close()!!}
   @endforeach
                            </td>
                            
                          </tr>

                        </tbody>
                      </table>
                    </div>
                  </div>
              </div>
                                </div>
                            </div>
                      
                        
                        </div>
                    </div></div>
                                            </div>
                </div>
                <!-- Content Wrapper END -->

                <!-- Footer START -->
                @stop  

resources/views/admin/slide/edit.blade.php
@extends('layouts.admin-master')
                             <!-- Content Wrapper START -->
@section('content')
                <div class="main-content">
                    <div class="container-fluid">
                        <div class="card">
                           <div class="col-md-12">
            <div class="panel panel-default">

              <div class="panel-body">
                
                <div class="tab-content br-n pn">
                 
                    <div class="row">
                      <div class="col-md-8"><br>
                        {!!Form::open(['method' => 'POST','action' =>[ 'PhotosController@update', $slides->id]])!!}
                                 
     <div class="form-group">
        <div class="col-sm-8">
     {!! Form::label('title','Title')!!}                            
    {{Form::text('name',$slides->text,['class'=>'form-control'])}}
    </div>
</div>
<div class="form-group">
    <div class="col-sm-8">
    {{Form::file('cover_image',['class'=>'form-control'])}}
</div>
</div>
<div class="form-group">
    <div class="col-sm-2">
      {{ Form::hidden('_method', 'PUT') }}
    {{Form::submit('submit',['class'=>'btn btn-primary'])}}
</div>
</div>
  {!! Form::close() !!}         
                                </div>
                               
                            </div>
                            
                                    
                                    </div><!--- -->
                                </div>
                            </div>
                      
                        
                        </div>
                    </div></div>
                                            </div>
                </div>
                <!-- Content Wrapper END -->
@stop
  

resources/views/admin/slide/index.blade.php
@extends('layouts.admin-master')
@section('content')
                <!-- Content Wrapper START -->

                <div class="main-content">
                    <div class="container-fluid">
                        <div class="card">
                           <div class="col-md-12">
            <div class="panel panel-default">

              <div class="panel-body">
                <ul class="nav nav-pills m-b-30 ">
                <li class="active nav-item "> <a href="#navpills-2" class="nav-link" data-toggle="tab" aria-expanded="false">List</a> </li>
                  <li class="nav-item"> <a href="#navpills-1" class="nav-link" data-toggle="tab" aria-expanded="false">Add</a> </li>
                     </ul>
                <div class="tab-content br-n pn">
                  <div id="navpills-1" class="tab-pane">
                    <div class="row">
                      <div class="col-md-8">
                                 {!!Form::open(['action' => 'PhotosController@store','method' => 'POST', 'enctype' => 'multipart/form-data'])!!}
     <div class="form-group">
        <div class="col-sm-8">
     {!! Form::label('title','Title')!!}                            
    {{Form::text('name','',['class'=>'form-control'])}}
    </div>
</div>
<div class="form-group">
    <div class="col-sm-8">
    {{Form::file('cover_image',['class'=>'form-control'])}}
</div>
</div>
<div class="form-group">
    <div class="col-sm-2">
    {{Form::submit('submit',['class'=>'btn btn-primary'])}}
</div>
</div>
  {!! Form::close() !!}   
                                </div>
                               
                            </div>
                            
                                    
                                    </div>
                                    <div id="navpills-2" class="tab-pane active">
                     <div class="row">                 
                   <div class="col-md-12">                     
                  <div class="whit-box">
                    <div class="table-responsive "><br><div class="col-md-8">@include('inc.message')</div><br>
                      <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered datatables" id="myTable">
                        <thead>
                          <tr>
                            <th class="center">Sl.</th>
                            <th class="center" >Title</th>
                            <th class="center">photo</th>

                            <th class="tdAction" align="center" width="120">Action</th>
                          </tr>
                        </thead>
                        <tbody>
                             @foreach($slides as $slide)
                          <tr class="odd" id="tR1">
                           
                            <td data-title="Serial"  width="30" align="right">{{$slide->id}}</td>
                           <td data-title="Serial"  >{{$slide->text}}</td>
                           

                            <td><img src="/album_covers/{{$slide->cover_image}}" width="100" height="60" alt="{{$slide->text}}"></td>

                            <td data-title="Action" align="center" width="120"><span id="deleteLoader1">&nbsp;</span>

                                
                              <a onclick="return confirm('Do you want to Edit?')" href="{{route('photos.edit',$slide->id)}}" class="btn btn-xs btn-green">
                    <i class="fa fa-pencil"></i>
                    </a>


                          {!!Form::open(['action' => ['PhotosController@destroy', $slide->id], 'method' => 'POST'])!!}
    {{Form::hidden('_method', 'DELETE')}}
    
                              {{Form::submit('Delete', ['class' => 'fa fa-trash-o'])}}
  {!!Form::close()!!}
   @endforeach
                            </td>
                            
                          </tr>

                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
                  </div>
              </div>
                                </div>
                            </div>
                      
                        
                        </div>
                    </div></div>
                                            </div>
                </div>
                <!-- Content Wrapper END -->

                <!-- Footer START -->
                @stop  