routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/',function(){
    return view('welcome');
});
Route::group(['prefix'=>'client'],function(){


    Route::get('index',function(){
        return view('client.index');
    });
    Route::get('about',function(){
        return view('client.about');
    });
    Route::get('blog',function(){
        return view('client.blog');
    });
    Route::get('account',function(){
        return view('client.my-account');
    });
    Route::get('event',function(){
        return view('client.event-detail');
    });
});


Route::group(['prefix'=>'admin'],function(){

//slide controller
Route::resource('photos','PhotosController');

//company-details controller

Route::resource('company-details','CompanysController');

//find-job controller
Route::resource('find-job','FindJobController');

//trust-us controller
Route::resource('trust-us','TrustUsController');

//event controller
Route::resource('event','EventController');

//testimonial controller
Route::resource('testimonial','TestimonialController');

//team controller
Route::resource('team','TeamController');

//dashboard controller
Route::resource('dashboard','DashboardController');

//profile controller
Route::resource('profile','ProfileController');
});





Auth::routes();
Route::get('logout','Auth\LoginController@logout')->name('logout');
Route::get('/home', 'HomeController@index')->name('home');

app/CompanyDetails.php
<?php

namespace App;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class CompanyDetails extends Model
{
    protected $fillable = array( 'company_name','company_photo','date','time');


    public function photos(){
      return $this->hasMany('App\Photo');
}
public function getTimeAttribute($value){
        return Carbon::parse($value)->format('g:i A');
    }

public function getDateAttribute($value){
        return Carbon::parse($value)->format('d-m-Y');
    }

}

resources/views/admin/company-details/create.blade.php
@extends('layouts.admin-master')
            @section('page-css')
<link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
@stop 
                <!-- Content Wrapper START -->
@section('content')
                <div class="main-content">
                    <div class="container-fluid">
                        <div class="card">
                           <div class="col-md-12">
            <div class="panel panel-default">

              <div class="panel-body">
                <ul class="nav nav-pills m-b-30 ">
                <li class="active nav-item "> <a href="#navpills-2" class="nav-link" data-toggle="tab" aria-expanded="false">List</a> </li>
                  <li class="nav-item"> <a href="#navpills-1" class="nav-link" data-toggle="tab" aria-expanded="false">Add</a> </li>
                     </ul>
                <div class="tab-content br-n pn">
                  <div id="navpills-1" class="tab-pane">
                    <div class="row">
                      <div class="col-md-8"><br>
                                 {!!Form::open(['action' => 'CompanysController@store','method' => 'POST', 'enctype' => 'multipart/form-data'])!!}
     <div class="form-group">
        <div class="col-sm-8">
     {!! Form::label('title','Company Name')!!}                            
    {{Form::text('company_name','',['class'=>'form-control'])}}
    </div>
</div>
<div class="form-group">
    <div class="col-sm-8">
    {{Form::file('company_photo',['class'=>'form-control'])}}
</div>
</div>
<div class="form-group">
        <div class="col-sm-8">
     {!! Form::label('title','Starts Date')!!}                            
    {{Form::text('start_date','',['class'=>'form-control','id'=>'input_time'])}}
    </div>
</div><br>
<div class="form-group">
        <div class="col-sm-8">
     {!! Form::label('title','End Date')!!}                            
    {{Form::text('end_date','',['class'=>'form-control','id'=>'input_endtime'])}}
    </div>
</div><br>
<div class="form-group">
    <div class="col-sm-2">

    {{Form::submit('submit',['class'=>'btn btn-primary'])}}
</div>
</div>
  {!! Form::close() !!}   
                                </div>
                               
                            </div>
                            
                                    
                                    </div>
                                    <div id="navpills-2" class="tab-pane active">
                  <div class="row">
                    <div class="table-responsive "><br><div class="col-md-8">@include('inc.message')</div>
                    <br>
                      <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered datatables" id="example">
                        <thead>
                          <tr>
                            <th class="center">Sl.</th>
                            <th class="center" >Company Name</th>
                            <th class="center">Company Photo</th>
                            <th class="center" >Date</th>
                            <th class="center" >Time</th>

                            <th class="tdAction" align="center" width="120">Action</th>
                          </tr>
                        </thead>
                        <tbody>
                             @foreach($companydetails as $companydetail)
                          <tr class="odd" id="tR1">
                           
                            <td data-title="Serial"  width="30" align="right">{{$companydetail->id}}</td>
                           <td data-title="Serial"  >{{$companydetail->company_name}}</td>
                           

                            <td><img src="/company/{{$companydetail->company_photo}}" width="100" height="60" alt="{{$companydetail->text}}"></td>
                             <td data-title="Serial"  >{{$companydetail->date}}</td>
                              <td data-title="Serial"  >{{$companydetail->time}}</td>
                            <td data-title="Action" align="center" width="120"><span id="deleteLoader1">&nbsp;</span>

                                
                              <a onclick="return confirm('Do you want to Edit?')" href="/company-details/{{$companydetail->id}}/edit" class="btn btn-xs btn-green">
                    <i class="fa fa-pencil"></i>    
                    </a>


                          {!!Form::open(['action' => ['CompanysController@destroy', $companydetail->id], 'method' => 'POST'])!!}
    {{Form::hidden('_method', 'DELETE')}}
    
                              {{Form::submit('Delete')}}
  {!!Form::close()!!}
   @endforeach
                            </td>
                            
                          </tr>

                        </tbody>
                      </table>
                    </div>
                  </div>
              </div>
                                </div>
                            </div>
                      
                        
                        </div>
                    </div></div>
                                            </div>
                </div>
                <!-- Content Wrapper END -->

                <!-- Footer START -->
              
@stop
@section('page-js')
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script><script type="text/javascript">
    $('#input_time').datepicker({
           dateFormat: 'dd-mm-yy',
            changeMonth: true,
          changeYear: true,
          yearRange: '1950:2050',
          showButtonPanel: true,
            maxDate: '0',
            onSelect: function(datetext){
                var d = new Date(); // for now
                var h = d.getHours();
                h = (h < 10) ? ("0" + h) : h ;
                var m = d.getMinutes();
                m = (m < 10) ? ("0" + m) : m ;
                var s = d.getSeconds();
                s = (s < 10) ? ("0" + s) : s ;
                datetext = datetext + " " + h + ":" + m + ":" + s;
                $('#input_time').val(datetext);
            },
    });
</script>
@stop
 
   

resources/views/admin/company-details/edit.blade.php
@extends('layouts.admin-master')
                             <!-- Content Wrapper START -->
@section('content')
                <div class="main-content">
                    <div class="container-fluid">
                        <div class="card">
                           <div class="col-md-12">
            <div class="panel panel-default">

              <div class="panel-body">
                
                <div class="tab-content br-n pn">
                 
                    <div class="row">
                      <div class="col-md-8"><br>
                                 {!!Form::open(['method' => 'POST','action' =>[ 'CompanysController@update', $companydetails->id]])!!}
     <div class="form-group">
        <div class="col-sm-8">
     {!! Form::label('title','Company Name')!!}                            
    {{Form::text('company_name',$companydetails->company_name,['class'=>'form-control'],$companydetails->company_name)}}
    </div>
</div>
<div class="form-group">
    <div class="col-sm-8">
    {{Form::file('company_photo',['class'=>'form-control'])}}
</div>
</div>
<div class="form-group">
        <div class="col-sm-8">
     {!! Form::label('title','Starts Date')!!}                            
    {{Form::text('start_date',$companydetails->start_date,['class'=>'form-control','id'=>'input_time'])}}
    </div>
</div><br>
<div class="form-group">
        <div class="col-sm-8">
     {!! Form::label('title','End Date')!!}                            
    {{Form::text('end_date',$companydetails->end_date,['class'=>'form-control','id'=>'input_endtime'])}}
    </div>
</div><br>

<div class="form-group">
    <div class="col-sm-2">
        {{ Form::hidden('_method', 'PUT') }}
    {{Form::submit('submit',['class'=>'btn btn-primary'])}}
</div>
</div>
  {!! Form::close() !!}   
                                </div>
                               
                            </div>
                            
                                    
                                    </div><!--- -->
                                </div>
                            </div>
                      
                        
                        </div>
                    </div></div>
                                            </div>
                </div>
                <!-- Content Wrapper END -->
@stop
   @section('page-js')
    

resources/views/admin/company-details/index.blade.php
@extends('layouts.admin-master')
      
                <!-- Content Wrapper START -->
@section('content')
                <div class="main-content">
                    <div class="container-fluid">
                        <div class="card">
                           <div class="col-md-12">
            <div class="panel panel-default">

              <div class="panel-body">
                <ul class="nav nav-pills m-b-30 ">
                <li class="active nav-item "> <a href="#navpills-2" class="nav-link" data-toggle="tab" aria-expanded="false">List</a> </li>
                  <li class="nav-item"> <a href="#navpills-1" class="nav-link" data-toggle="tab" aria-expanded="false">Add</a> </li>
                     </ul>
                <div class="tab-content br-n pn">
                  <div id="navpills-1" class="tab-pane">
                    <div class="row">
                      <div class="col-md-8"><br>
                                 {!!Form::open(['action' => 'CompanysController@store','method' => 'POST', 'enctype' => 'multipart/form-data'])!!}
     <div class="form-group">
        <div class="col-sm-8">
     {!! Form::label('title','Company Name')!!}                            
    {{Form::text('company_name','',['class'=>'form-control'])}}
    </div>
</div>
<div class="form-group">
    <div class="col-sm-8">
    {{Form::file('company_photo',['class'=>'form-control'])}}
</div>
</div>
<div class="form-group">
        <div class="col-sm-8">
     {!! Form::label('title','Starts Date')!!}                            
    {{Form::text('start_date','',['class'=>'form-control','id'=>'input_time'])}}
    </div>
</div><br>
<div class="form-group">
        <div class="col-sm-8">
     {!! Form::label('title','End Date')!!}                            
    {{Form::text('end_date','',['class'=>'form-control','id'=>'input_endtime'])}}
    </div>
</div><br>
<div class="form-group">
    <div class="col-sm-2">

    {{Form::submit('submit',['class'=>'btn btn-primary'])}}
</div>
</div>
  {!! Form::close() !!}   
                                </div>
                               
                            </div>
                            
                                    
                                    </div>
                                    <div id="navpills-2" class="tab-pane active">
                  <div class="row">
                    <div class="table-responsive "><br><div class="col-md-8">@include('inc.message')</div>
                    <br>
                      <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered datatables" id="myTable">
                        <thead>
                          <tr>
                            <th class="center">Sl.</th>
                            <th class="center" >Company Name</th>
                            <th class="center">Company Photo</th>
                            <th class="center" >Start Date</th>
                            <th class="center" >End Date</th>

                            <th class="tdAction" align="center" width="120">Action</th>
                          </tr>
                        </thead>
                        <tbody>
                             @foreach($companydetails as $companydetail)
                          <tr class="odd" id="tR1">
                           
                            <td data-title="Serial"  width="30" align="right">{{$companydetail->id}}</td>
                           <td data-title="Serial"  >{{$companydetail->company_name}}</td>
                           

                            <td><img src="/company/{{$companydetail->company_photo}}" width="100" height="60" alt="{{$companydetail->text}}"></td>
                             <td data-title="Serial"  >{{$companydetail->start_date}}</td>
                              <td data-title="Serial"  >{{$companydetail->end_date}}</td>
                            <td data-title="Action" align="center" width="120"><span id="deleteLoader1">&nbsp;</span>

                                
                              <a onclick="return confirm('Do you want to Edit?')" href="{{route('company-details.edit',$companydetail->id)}}"" class="btn btn-xs btn-green">
                    <i class="fa fa-pencil"></i>    
                    </a>


                          {!!Form::open(['action' => ['CompanysController@destroy', $companydetail->id], 'method' => 'POST'])!!}
    {{Form::hidden('_method', 'DELETE')}}
    
                              {{Form::submit('Delete')}}
  {!!Form::close()!!}
   @endforeach
                            </td>
                            
                          </tr>

                        </tbody>
                      </table>
                    </div>
                  </div>
              </div>
                                </div>
                            </div>
                      
                        
                        </div>
                    </div></div>
                                            </div>
                </div>
                <!-- Content Wrapper END -->

                <!-- Footer START -->
              
@stop


 
   