routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/',function(){
    return view('welcome');
});
Route::group(['prefix'=>'client'],function(){


    Route::get('index',function(){
        return view('client.index');
    });
    Route::get('about',function(){
        return view('client.about');
    });
    Route::get('blog',function(){
        return view('client.blog');
    });
    Route::get('account',function(){
        return view('client.my-account');
    });
    Route::get('event',function(){
        return view('client.event-detail');
    });
});


Route::group(['prefix'=>'admin'],function(){

//slide controller
Route::resource('photos','PhotosController');

//company-details controller

Route::resource('company-details','CompanysController');

//find-job controller
Route::resource('find-job','FindJobController');

//trust-us controller
Route::resource('trust-us','TrustUsController');

//event controller
Route::resource('event','EventController');

//testimonial controller
Route::resource('testimonial','TestimonialController');

//team controller
Route::resource('team','TeamController');

//dashboard controller
Route::resource('dashboard','DashboardController');

//profile controller
Route::resource('profile','ProfileController');
});





Auth::routes();
Route::get('logout','Auth\LoginController@logout')->name('logout');
Route::get('/home', 'HomeController@index')->name('home');

resources/views/layouts/admin-master.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no">
    <title>Espire - Bootstrap 4 Admin Template</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="/public/images/logo/favicon.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <!-- plugins css -->

    <!-- core css -->
    <link href="{{asset('css/ei-icon.css')}}" rel="stylesheet">
    <link href="{{asset('css/themify-icons.css')}}" rel="stylesheet">
    <link href="{{asset('css/font-awesome.min.css')}}" rel="stylesheet">
    <link href="{{asset('css/animate.min.css')}}" rel="stylesheet">
    <link href="{{asset('css/app.css')}}" rel="stylesheet">
    <link href="{{asset('css/jquery.dataTables.min.css')}}" rel="stylesheet" >
<link href = "https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css"
         rel = "stylesheet">


</head>

<body>
    <div class="app">
        <div class="layout">
            <!-- Side Nav START -->
            <div class="side-nav">
                <div class="side-nav-inner">
                    <div class="side-nav-logo">
                        <a href="{{route('dashboard.index')}}">
                            <div class="logo logo-dark" style="background-image: url('/images/logo/logo.png')"></div>
                            <div class="logo logo-white" style="background-image: url('/images/logo/logo-white.png')"></div>
                        </a>
                        <div class="mobile-toggle side-nav-toggle">
                            <a href="">
                                <i class="ti-arrow-circle-left"></i>
                            </a>
                        </div>
                    </div>
                    <ul class="side-nav-menu scrollable">
                        <li class="nav-item active">
                            <a class="mrg-top-30" href="{{route('dashboard.index')}}">
                                <span class="icon-holder">
										<i class="ti-home"></i>
									</span>
                                <span class="title">Dashboard</span>
                            </a>
                        </li>
                        <li class="nav-item active">
                            <a class="text" href="{{route('photos.index')}}">
                                <span class="icon-holder">
                                        <i class="ti-plus"></i>
                                    </span>
                                <span class="title">Add Slide</span>
                            </a>
                        </li>
                        <li class="nav-item active">
                            <a class="text" href="{{route('company-details.index')}}">
                                <span class="icon-holder">
                                        <i class="ti-info"></i>
                                    </span>
                                <span class="title">Company details</span>
                            </a>
                        </li>
                        <li class="nav-item active">
                            <a class="text" href="{{route('find-job.index')}}">
                                <span class="icon-holder">
                                        <i class="fa fa-tasks"></i>
                                    </span>
                                <span class="title">Find Job</span>
                            </a>
                        </li>
                        <li class="nav-item active">
                            <a class="text" href="{{route('trust-us.index')}}">
                                <span class="icon-holder">
                                        <i class="fa fa-handshake-o"></i>
                                    </span>
                                <span class="title">Trust Us Partners</span>
                            </a>
                        </li>
                        <li class="nav-item active">
                            <a class="text" href="{{route('event.index')}}">
                                <span class="icon-holder">
                                        <i class="fa fa-calendar"></i>
                                    </span>
                                <span class="title">Events</span>
                            </a>
                        </li>
                        <li class="nav-item active">
                            <a class="text" href="{{route('testimonial.index')}}">
                                <span class="icon-holder">
                                        <i class="fa fa-quote-left"></i>
                                    </span>
                                <span class="title">Testimonials</span>
                            </a>
                        </li>
                        <li class="nav-item active">
                            <a class="text" href="{{route('team.index')}}">
                                <span class="icon-holder">
                                        <i class="fa fa-group"></i>
                                    </span>
                                <span class="title">Our Teams</span>
                            </a>
                        </li>

                     </ul>

				</div>
            </div>
            <!-- Side Nav END -->

            <!-- Page Container START -->
            <div class="page-container">
                <!-- Header START -->
                <div class="header navbar">
                    <div class="header-container">
                        <ul class="nav-left">
                            <li>
                                <a class="side-nav-toggle" href="javascript:void(0);">
                                    <i class="ti-view-grid"></i>
                                </a>
                            </li>


                        </ul>
                        <ul class="nav-right">
                            <li class="user-profile dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown">
                                    <img class="profile-img img-fluid" src="/images/user.jpg" alt="">

                                </a>
                                <ul class="dropdown-menu">

                                    <li>
                                        <a href="{{route('profile.index')}}">
                                            <i class="ti-user pdd-right-10"></i>
                                            <span>Profile</span>
                                        </a>
                                    </li>

                                    <li role="separator" class="divider"></li>
                                     <li>
                                        <a href="account.php">
                                            <i class="ti-power-off pdd-right-10"></i>
                                            <span>Logout</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>




                        </ul>
                    </div>
                </div>
                <!-- Header END -->







                <!-- Content Wrapper START -->

                @yield('content')
                <!-- Content Wrapper END -->

                <!-- Footer START -->
                <footer class="content-footer">
                    <div class="footer">
                        <div class="copyright">
                            <span>Copyright © 2017 <b class="text-dark">Theme_Nate</b>. All rights reserved.</span>
                            <span class="go-right">
									<a href="" class="text-gray mrg-right-15">Term &amp; Conditions</a>
									<a href="" class="text-gray">Privacy &amp; Policy</a>
								</span>
                        </div>
                    </div>
                </footer>
                <!-- Footer END -->

            </div>
            <!-- Page Container END -->

        </div>
    </div>


    <!-- core js -->
    <script src="{{asset('js/app.js')}}" type="text/javascript"></script>
 <script src="{{asset('js/app.js')}}" type="text/javascript"></script>
<script src="{{asset('js/jquery.dataTables.min.js')}}" type="text/javascript"></script>
      <script src="{{asset('js/data-table.js')}}" type="text/javascript"></script>
      <script src="{{asset('js/bootstrap-datepicker.js')}}"></script>
      <script src="{{asset('js/perfect-scrollbar.jquery.js')}}"></script>
      <script src="{{asset('js/perfect-scrollbar.jquery.min.js')}}"></script>
      <script src="{{asset('js/perfect-scrollbar.js')}}"></script>
      <script src="{{asset('js/perfect-scrollbar.min.js')}}"></script>
        <script src = "https://code.jquery.com/jquery-1.10.2.js"></script>
      <script src = "https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
  <script >
    $('#input_time').datepicker({
           dateFormat: 'dd-mm-yy',
            changeMonth: true,
          changeYear: true,
          yearRange: '1950:2050',
          showButtonPanel: true,
            maxDate: '0',
            onSelect: function(datetext){
                var d = new Date(); // for now
                var h = d.getHours();
                h = (h < 10) ? ("0" + h) : h ;
                var m = d.getMinutes();
                m = (m < 10) ? ("0" + m) : m ;
                var s = d.getSeconds();
                s = (s < 10) ? ("0" + s) : s ;
                datetext = datetext + " " + h + ":" + m + ":" + s;
                $('#input_time').val(datetext);
            },
    });
     $('#input_endtime').datepicker({
           dateFormat: 'dd-mm-yy',
            changeMonth: true,
          changeYear: true,
          yearRange: '1950:2050',
          showButtonPanel: true,
            maxDate: '0',
            onSelect: function(datetext){
                var d = new Date(); // for now
                var h = d.getHours();
                h = (h < 10) ? ("0" + h) : h ;
                var m = d.getMinutes();
                m = (m < 10) ? ("0" + m) : m ;
                var s = d.getSeconds();
                s = (s < 10) ? ("0" + s) : s ;
                datetext = datetext + " " + h + ":" + m + ":" + s;
                $('#input_endtime').val(datetext);
            },
    });
</script>

      <script>
     $(document).ready(function() {
        $('#myTable').DataTable();
        $(document).ready(function() {
            var table = $('#example').DataTable({
                "columnDefs": [{
                    "visible": false,
                    "targets": 2
                }],
                "order": [
                    [2, 'asc']
                ],
                "displayLength": 25,
                "drawCallback": function(settings) {
                    var api = this.api();
                    var rows = api.rows({
                        page: 'current'
                    }).nodes();
                    var last = null;
                    api.column(2, {
                        page: 'current'
                    }).data().each(function(group, i) {
                        if (last !== group) {
                            $(rows).eq(i).before('<tr class="group"><td colspan="5">' + group + '</td></tr>');
                            last = group;
                        }
                    });
                }
            });
            // Order by the grouping
            $('#example tbody').on('click', 'tr.group', function() {
                var currentOrder = table.order()[0];
                if (currentOrder[0] === 2 && currentOrder[1] === 'asc') {
                    table.order([2, 'desc']).draw();
                } else {
                    table.order([2, 'asc']).draw();
                }
            });
        });
    });
    </script>
    @section('page-js')

    <script src="js/bootstrap-datepicker.js"></script>

    <!-- page js -->
    <script >
         $( document ).ready(function() {
          $('#input_starttime').timepicker({

    // 12 or 24 hour
    twelvehour: true,
    timeFormat: 'h:mm p',
    dynamic: true,
    dropdown: true,
    scrollbar: true
});
    });

    </script>
 
    <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>




@stop

</body>

</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/client-master.blade.php
<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Home | Incubateind</title>
<link rel="shortcut icon" href="img/favicon.png" type="image/x-icon">
<link rel="stylesheet" href="{{ asset('css/bootstrap.min.css')}}">
<link rel="stylesheet" href="{{ asset('css/style.css')}}">
<link rel="stylesheet" href="{{ asset('css/swiper.min.css')}}">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="stylesheet">
@yield('page-css')
</head>

<body>
<div class="overlay"></div>
  <div id="overlay">
    <div class="loader">
      <div class="circle"></div>
      <div class="circle"></div>
      <div class="circle"></div>
    </div>
  </div>
  <!--<div class="chat"><a href="#"><img src="img/chat.svg" alt=""></a></div>-->
  <!-- Header-->
  <header>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
		  <div class="menu-overlay"></div>
		<!-- Logo & Hamburger Menu -->
        <div class="navbar-header">
          <div class="hamburger">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          </div>
          <a class="navbar-brand" href="index.html"><img src="{{asset('img/logo.svg')}}" alt=""></a>
		</div>

		<!-- Login & Signup -->
		<div class="login-signup">
			<!-- Before Login -->
			<div class="login">
				@if(Auth::user())
					<a href="{{ route('logout') }}">LogOut</a>
				@else
				<a href="#" id="login-signup">Login/Sign up</a>
				@endif
			</div>
			<!-- After Login -->
			<!--<ul class="logged-in">
				<li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle"><img src="img/default-profile.svg" alt=""><img src="img/down-arrow.svg" alt="" class="down-arrow"></a>
					<ul class="dropdown-menu">
						<h3>Hi,</h3>
						<p>Kapoor.varun4@gmail.com</p>
						<a href="index.html" class="border-button">Sign out</a>
					</ul>
				</li>
		    </ul> -->
	   </div>
		<!-- Menu -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		  <!-- Search bar -->
		  <div class="search-bar">
			  <form action="search-results.html">
		  		<div class="dropdown"><input type="search" placeholder="Search for an Events" data-toggle="drodown" class="dropdown-toggle">
				 <div class="blogs popular-search">
					<ul class="dropdown-menu">
						<p>Popular Search</p>
						<li><a href="blog-detail.html"><div class="thubnail"><img src="{{asset('img/blog/thumbnail/one.png')}}" alt=""></div><div class="elipsis-text"><h4>Using Artificial Intelligence, Chatbots will be imaginative – Gaurav</h4></div></a></li>
						<li><a href="blog-detail.html"><div class="thubnail"><img src="{{asset('img/blog/thumbnail/two.png')}}" alt=""></div><div class="elipsis-text"><h4>Technologies like Artificial Intelligence can make rental market Robus</h4></div></a></li>
						<li><a href="blog-detail.html"><div class="thubnail"><img src="{{asset('img/blog/thumbnail/three.png')}}" alt=""></div><div class="elipsis-text"><h4>Big Data and Artificial Intelligence are changing the world in a dram</h4></div></a></li>
						<li><a href="blog-detail.html"><div class="thubnail"><img src="{{asset('img/blog/thumbnail/four.png')}}" alt=""></div><div class="elipsis-text"><h4>Maharashtra`s IT Dept signs a MoU with University of Southern California</h4></div></a></li>
			 		 </ul>
				</div>
				 </div>
		     </form>
		  </div>
          <ul class="nav navbar-nav pull-right" id="mainNav">
            <li><a href="about-us.html">About Us</a></li>
            <li class="blogs events dropdown"><a href="event-detail.html" class="dropdown-toggle">Events <img src="{{asset('img/down-arrow.svg')}}" alt=""></a>
			  <ul class="dropdown-menu">
				<li><a href="#"><div class="thubnail"><img src="{{asset('img/blog/thumbnail/one.png')}}" alt=""></div><h3>Intel</h3><div class="elipsis-text"><h4>Using Artificial Intelligence, Chatbots</h4></div><p>upcoming event</p> </a></li>
				<li><a href="#"><div class="thubnail"><img src="{{asset('img/blog/thumbnail/two.png')}}" alt=""></div><h3>Microsoft</h3><div class="elipsis-text"><h4>Technologies like Artificial</h4></div><p>Upcoming Event</p></a></li>
				<li><a href="#"><div class="thubnail"><img src="{{asset('img/blog/thumbnail/three.png')}}" alt=""></div><h3>Dish a thon</h3><div class="elipsis-text"><h4>Big Data and Artificial Intelligence</h4></div><p>Upcoming Event</p></a></li>
				<li><a href="#"><div class="thubnail"><img src="{{asset('img/blog/thumbnail/four.png')}}" alt=""></div><h3>Vistara</h3><div class="elipsis-text"><h4>Maharashtr`s IT Dept</h4></div><p>Upcoming Event</p></a></li>
				<li class="see-all"><a href="search-results.html" class="border-button">see all events</a></li>
			  </ul>
			</li>
            <li class="blogs dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Blogs <img src="{{asset('img/down-arrow.svg')}}" alt=""></a>
			  <ul class="dropdown-menu">
				<li><a href="blog-detail.html"><div class="thubnail"><img src="{{asset('img/blog/thumbnail/one.png')}}" alt=""></div><div class="elipsis-text"><h4>Using Artificial Intelligence, Chatbots will be imaginative – Gaurav</h4></div></a></li>
				<li><a href="blog-detail.html"><div class="thubnail"><img src="{{asset('img/blog/thumbnail/two.png')}}" alt=""></div><div class="elipsis-text"><h4>Technologies like Artificial Intelligence can make rental market Robus</h4></div></a></li>
				<li><a href="blog-detail.html"><div class="thubnail"><img src="{{asset('img/blog/thumbnail/three.png')}}" alt=""></div><div class="elipsis-text"><h4>Big Data and Artificial Intelligence are changing the world in a dram</h4></div></a></li>
				<li><a href="blog-detail.html"><div class="thubnail"><img src="{{asset('img/blog/thumbnail/four.png')}}" alt=""></div><div class="elipsis-text"><h4>Maharashtra`s IT Dept signs a MoU with University of Southern California</h4></div></a></li>
				  <li class="see-all"><a href="blog.html" class="border-button">see all blogs</a></li>
			  </ul>
			</li>
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <!-- Site Wrapper -->
<div class="site-wrapper">
@yield('content')
</div>

	<!-- Footer -->
	<footer class="footer">
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<div class="logo"><a href="index.html"><img src="{{asset('img/logo-white.svg')}}" alt="Logo"></a></div>
				  <div class="keep-in-touch">
						<h6>Keep in touch</h6>
					<ul class="social-links">
							<li><a href="https://www.linkedin.com/company/incubateind?originalSubdomain=in" target="_blank"><img src="{{asset('img/linkedin.svg')}}" alt="linkedin"></a></li>
							<li><a href="https://twitter.com/incubateind?lang=en"><img src="{{asset('img/twitter.svg')}}" alt="twitter"></a></li>
							<li><a href="https://www.youtube.com/channel/UCcgyWC65tim3f3SMSZaMQ2w"><img src="{{asset('img/youtube.svg')}}" alt="youtube"></a></li>
							<li><a href="https://www.instagram.com/incubateindia/"><img src="{{asset('img/instagram.svg')}}" alt="instagram"></a></li>
							<li><a href="#"><img src="{{asset('img/telegram.svg')}}" alt="telegram"></a></li>
					  </ul>
					</div>
				</div>
				<div class="col-md-8">
					<div class="col-md-3">
						<h6>Company</h6>
						<ul>
							<li><a href="javascript:void(0)">About Us</a></li>
							<li><a href="javascript:void(0)">Careers</a></li>
							<li><a href="javascript:void(0)">Blog</a></li>
							<li><a href="javascript:void(0)">Privacy Policy</a></li>
							<li><a href="javascript:void(0)">Contact Us</a></li>
						</ul>
					</div>
					<div class="col-md-4 col-push-1">
						<h6>Developers</h6>
						<ul>
							<li><a href="javascript:void(0)">Scoring</a></li>
							<li><a href="javascript:void(0)">Environment</a></li>
							<li><a href="javascript:void(0)">FAQ</a></li>
							<li><a href="javascript:void(0)">For Schools</a></li>
							<li><a href="javascript:void(0)">Sign up</a></li>
						</ul>
					</div>
					<div class="col-md-3 col-offset-1">
						<h6>Companies</h6>
						<ul>
							<li><a href="javascript:void(0)">Solutions</a></li>
							<li><a href="javascript:void(0)">Customers</a></li>
							<li><a href="javascript:void(0)">Pricing</a></li>
							<li><a href="javascript:void(0)">Try for Free</a></li>
							<li><a href="javascript:void(0)">Terms of Service</a></li>
						</ul>
					</div>
					<div class="col-md-2">
						<h6>Resources</h6>
						<ul>
							<li><a href="javascript:void(0)">API</a></li>
							<li><a href="javascript:void(0)">Guides</a></li>
							<li><a href="javascript:void(0)">Partners</a></li>
							<li><a href="javascript:void(0)">Events</a></li>
							<li><a href="javascript:void(0)">News</a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="copyright">Copyright &copy; 2018 IncubateIND.Com, All rights reserved.</div>
		</div>
		 <div id="go-top"> <a href="#"><img src="{{asset('img/arrow-up.svg')}}" alt=""> </a></div>
	</footer>
<script src="{{asset('js/jquery-3.3.1.min.js')}}" type="text/javascript"></script>
<script src="{{asset('js/bootstrap.min.js')}}" type="text/javascript"></script>
<script src="{{asset('js/swiper.min.js')}}" type="text/javascript"></script>
<script src="{{asset('js/main.js')}}" type="text/javascript"></script>
<script src="{{asset('js/common-slider.js')}}" type="text/javascript"></script>

</body>
</html>